# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kiln < Formula
  desc ""
  homepage ""
  version "0.115.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pivotal-cf/kiln/releases/download/v0.115.0/kiln-darwin-amd64-0.115.0.tar.gz"
      sha256 "48e37602112fc04a1ac3154477deba3571198578c55e9545fd91564dc93254d4"

      define_method(:install) do
        bin.install "kiln"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pivotal-cf/kiln/releases/download/v0.115.0/kiln-darwin-arm64-0.115.0.tar.gz"
      sha256 "d04e01519343dbbbe9bcf5784de43785b755b89b414c9733af3b76a155e7bd7d"

      define_method(:install) do
        bin.install "kiln"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pivotal-cf/kiln/releases/download/v0.115.0/kiln-linux-amd64-0.115.0.tar.gz"
      sha256 "02d7fdcb9021e197cd2b42c4b1ad66a2a21aff19795b7b9060b325f2606c60f8"
      define_method(:install) do
        bin.install "kiln"
      end
    end
  end

  test do
    system "#{bin}/kiln --version"
  end
end
