# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kiln < Formula
  desc ""
  homepage ""
  version "0.88.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pivotal-cf/kiln/releases/download/v0.88.0/kiln-darwin-arm64-0.88.0.tar.gz"
      sha256 "049eeab5a08b4ea98a945e715c221eb676fcc4867f6fd680f78f1693aa7c253d"

      def install
        bin.install "kiln"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pivotal-cf/kiln/releases/download/v0.88.0/kiln-darwin-amd64-0.88.0.tar.gz"
      sha256 "d299144e02079fb8fa6687c5cc5792628bbf6718ed4713992780b4971d16af63"

      def install
        bin.install "kiln"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pivotal-cf/kiln/releases/download/v0.88.0/kiln-linux-amd64-0.88.0.tar.gz"
      sha256 "25f1882f06a18bb7eae9d6e968a946fc8d4f8afd18fcbc3544e899ca4d5c8b53"

      def install
        bin.install "kiln"
      end
    end
  end

  test do
    system "#{bin}/kiln --version"
  end
end
