# For documentation at http://goreleaser.com
version: 2
before:
  hooks:
    - go mod download
release:
  github:
    owner: pivotal-cf
    name: kiln
  prerelease: auto
builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - windows_amd64
      - darwin_amd64
      - darwin_arm64
    ldflags:
      - -X "main.version={{.Version}}"
    main: ./
archives:
  - id: github
    formats:
      - "binary"
    name_template: "kiln-{{ .Os }}-{{ .Arch }}-{{ .Version }}"
  - id: homebrew
    formats:
      - "tar.gz"
    name_template: "kiln-{{ .Os }}-{{ .Arch }}-{{ .Version }}"
    format_overrides:
      - goos: windows
        formats:
          - "zip"
brews:
  - name: kiln
    repository:
      owner: pivotal-cf
      name: kiln
      token: "{{ .Env.GITHUB_TOKEN }}"
    directory: HomebrewFormula
    ids:
      - homebrew
    test: |
      system "#{bin}/kiln --version"

dockers:
  - image_templates:
      - "pivotalcfreleng/kiln:latest"
      - "pivotalcfreleng/kiln:{{ .Tag }}"

    skip_push: false

    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  disable: true
