// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/pivotal-cf/kiln/commands"
	"github.com/pivotal-cf/kiln/internal/cargo"
	"github.com/pivotal-cf/kiln/release"
)

type LocalReleaseDirectory struct {
	DeleteExtraReleasesStub        func(release.LocalReleaseSet, bool) error
	deleteExtraReleasesMutex       sync.RWMutex
	deleteExtraReleasesArgsForCall []struct {
		arg1 release.LocalReleaseSet
		arg2 bool
	}
	deleteExtraReleasesReturns struct {
		result1 error
	}
	deleteExtraReleasesReturnsOnCall map[int]struct {
		result1 error
	}
	GetLocalReleasesStub        func(string) ([]release.SatisfyingLocalRelease, error)
	getLocalReleasesMutex       sync.RWMutex
	getLocalReleasesArgsForCall []struct {
		arg1 string
	}
	getLocalReleasesReturns struct {
		result1 []release.SatisfyingLocalRelease
		result2 error
	}
	getLocalReleasesReturnsOnCall map[int]struct {
		result1 []release.SatisfyingLocalRelease
		result2 error
	}
	VerifyChecksumsStub        func(release.LocalReleaseSet, cargo.KilnfileLock) error
	verifyChecksumsMutex       sync.RWMutex
	verifyChecksumsArgsForCall []struct {
		arg1 release.LocalReleaseSet
		arg2 cargo.KilnfileLock
	}
	verifyChecksumsReturns struct {
		result1 error
	}
	verifyChecksumsReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *LocalReleaseDirectory) DeleteExtraReleases(arg1 release.LocalReleaseSet, arg2 bool) error {
	fake.deleteExtraReleasesMutex.Lock()
	ret, specificReturn := fake.deleteExtraReleasesReturnsOnCall[len(fake.deleteExtraReleasesArgsForCall)]
	fake.deleteExtraReleasesArgsForCall = append(fake.deleteExtraReleasesArgsForCall, struct {
		arg1 release.LocalReleaseSet
		arg2 bool
	}{arg1, arg2})
	fake.recordInvocation("DeleteExtraReleases", []interface{}{arg1, arg2})
	fake.deleteExtraReleasesMutex.Unlock()
	if fake.DeleteExtraReleasesStub != nil {
		return fake.DeleteExtraReleasesStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.deleteExtraReleasesReturns
	return fakeReturns.result1
}

func (fake *LocalReleaseDirectory) DeleteExtraReleasesCallCount() int {
	fake.deleteExtraReleasesMutex.RLock()
	defer fake.deleteExtraReleasesMutex.RUnlock()
	return len(fake.deleteExtraReleasesArgsForCall)
}

func (fake *LocalReleaseDirectory) DeleteExtraReleasesCalls(stub func(release.LocalReleaseSet, bool) error) {
	fake.deleteExtraReleasesMutex.Lock()
	defer fake.deleteExtraReleasesMutex.Unlock()
	fake.DeleteExtraReleasesStub = stub
}

func (fake *LocalReleaseDirectory) DeleteExtraReleasesArgsForCall(i int) (release.LocalReleaseSet, bool) {
	fake.deleteExtraReleasesMutex.RLock()
	defer fake.deleteExtraReleasesMutex.RUnlock()
	argsForCall := fake.deleteExtraReleasesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *LocalReleaseDirectory) DeleteExtraReleasesReturns(result1 error) {
	fake.deleteExtraReleasesMutex.Lock()
	defer fake.deleteExtraReleasesMutex.Unlock()
	fake.DeleteExtraReleasesStub = nil
	fake.deleteExtraReleasesReturns = struct {
		result1 error
	}{result1}
}

func (fake *LocalReleaseDirectory) DeleteExtraReleasesReturnsOnCall(i int, result1 error) {
	fake.deleteExtraReleasesMutex.Lock()
	defer fake.deleteExtraReleasesMutex.Unlock()
	fake.DeleteExtraReleasesStub = nil
	if fake.deleteExtraReleasesReturnsOnCall == nil {
		fake.deleteExtraReleasesReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteExtraReleasesReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *LocalReleaseDirectory) GetLocalReleases(arg1 string) ([]release.SatisfyingLocalRelease, error) {
	fake.getLocalReleasesMutex.Lock()
	ret, specificReturn := fake.getLocalReleasesReturnsOnCall[len(fake.getLocalReleasesArgsForCall)]
	fake.getLocalReleasesArgsForCall = append(fake.getLocalReleasesArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("GetLocalReleases", []interface{}{arg1})
	fake.getLocalReleasesMutex.Unlock()
	if fake.GetLocalReleasesStub != nil {
		return fake.GetLocalReleasesStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getLocalReleasesReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *LocalReleaseDirectory) GetLocalReleasesCallCount() int {
	fake.getLocalReleasesMutex.RLock()
	defer fake.getLocalReleasesMutex.RUnlock()
	return len(fake.getLocalReleasesArgsForCall)
}

func (fake *LocalReleaseDirectory) GetLocalReleasesCalls(stub func(string) ([]release.SatisfyingLocalRelease, error)) {
	fake.getLocalReleasesMutex.Lock()
	defer fake.getLocalReleasesMutex.Unlock()
	fake.GetLocalReleasesStub = stub
}

func (fake *LocalReleaseDirectory) GetLocalReleasesArgsForCall(i int) string {
	fake.getLocalReleasesMutex.RLock()
	defer fake.getLocalReleasesMutex.RUnlock()
	argsForCall := fake.getLocalReleasesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *LocalReleaseDirectory) GetLocalReleasesReturns(result1 []release.SatisfyingLocalRelease, result2 error) {
	fake.getLocalReleasesMutex.Lock()
	defer fake.getLocalReleasesMutex.Unlock()
	fake.GetLocalReleasesStub = nil
	fake.getLocalReleasesReturns = struct {
		result1 []release.SatisfyingLocalRelease
		result2 error
	}{result1, result2}
}

func (fake *LocalReleaseDirectory) GetLocalReleasesReturnsOnCall(i int, result1 []release.SatisfyingLocalRelease, result2 error) {
	fake.getLocalReleasesMutex.Lock()
	defer fake.getLocalReleasesMutex.Unlock()
	fake.GetLocalReleasesStub = nil
	if fake.getLocalReleasesReturnsOnCall == nil {
		fake.getLocalReleasesReturnsOnCall = make(map[int]struct {
			result1 []release.SatisfyingLocalRelease
			result2 error
		})
	}
	fake.getLocalReleasesReturnsOnCall[i] = struct {
		result1 []release.SatisfyingLocalRelease
		result2 error
	}{result1, result2}
}

func (fake *LocalReleaseDirectory) VerifyChecksums(arg1 release.LocalReleaseSet, arg2 cargo.KilnfileLock) error {
	fake.verifyChecksumsMutex.Lock()
	ret, specificReturn := fake.verifyChecksumsReturnsOnCall[len(fake.verifyChecksumsArgsForCall)]
	fake.verifyChecksumsArgsForCall = append(fake.verifyChecksumsArgsForCall, struct {
		arg1 release.LocalReleaseSet
		arg2 cargo.KilnfileLock
	}{arg1, arg2})
	fake.recordInvocation("VerifyChecksums", []interface{}{arg1, arg2})
	fake.verifyChecksumsMutex.Unlock()
	if fake.VerifyChecksumsStub != nil {
		return fake.VerifyChecksumsStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.verifyChecksumsReturns
	return fakeReturns.result1
}

func (fake *LocalReleaseDirectory) VerifyChecksumsCallCount() int {
	fake.verifyChecksumsMutex.RLock()
	defer fake.verifyChecksumsMutex.RUnlock()
	return len(fake.verifyChecksumsArgsForCall)
}

func (fake *LocalReleaseDirectory) VerifyChecksumsCalls(stub func(release.LocalReleaseSet, cargo.KilnfileLock) error) {
	fake.verifyChecksumsMutex.Lock()
	defer fake.verifyChecksumsMutex.Unlock()
	fake.VerifyChecksumsStub = stub
}

func (fake *LocalReleaseDirectory) VerifyChecksumsArgsForCall(i int) (release.LocalReleaseSet, cargo.KilnfileLock) {
	fake.verifyChecksumsMutex.RLock()
	defer fake.verifyChecksumsMutex.RUnlock()
	argsForCall := fake.verifyChecksumsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *LocalReleaseDirectory) VerifyChecksumsReturns(result1 error) {
	fake.verifyChecksumsMutex.Lock()
	defer fake.verifyChecksumsMutex.Unlock()
	fake.VerifyChecksumsStub = nil
	fake.verifyChecksumsReturns = struct {
		result1 error
	}{result1}
}

func (fake *LocalReleaseDirectory) VerifyChecksumsReturnsOnCall(i int, result1 error) {
	fake.verifyChecksumsMutex.Lock()
	defer fake.verifyChecksumsMutex.Unlock()
	fake.VerifyChecksumsStub = nil
	if fake.verifyChecksumsReturnsOnCall == nil {
		fake.verifyChecksumsReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.verifyChecksumsReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *LocalReleaseDirectory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.deleteExtraReleasesMutex.RLock()
	defer fake.deleteExtraReleasesMutex.RUnlock()
	fake.getLocalReleasesMutex.RLock()
	defer fake.getLocalReleasesMutex.RUnlock()
	fake.verifyChecksumsMutex.RLock()
	defer fake.verifyChecksumsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *LocalReleaseDirectory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ commands.LocalReleaseDirectory = new(LocalReleaseDirectory)
