// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/pivotal-cf/kiln/kiln"
)

type ArgParser struct {
	ParseStub        func([]string) (kiln.ApplicationConfig, error)
	parseMutex       sync.RWMutex
	parseArgsForCall []struct {
		arg1 []string
	}
	parseReturns struct {
		result1 kiln.ApplicationConfig
		result2 error
	}
	parseReturnsOnCall map[int]struct {
		result1 kiln.ApplicationConfig
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ArgParser) Parse(arg1 []string) (kiln.ApplicationConfig, error) {
	var arg1Copy []string
	if arg1 != nil {
		arg1Copy = make([]string, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.parseMutex.Lock()
	ret, specificReturn := fake.parseReturnsOnCall[len(fake.parseArgsForCall)]
	fake.parseArgsForCall = append(fake.parseArgsForCall, struct {
		arg1 []string
	}{arg1Copy})
	fake.recordInvocation("Parse", []interface{}{arg1Copy})
	fake.parseMutex.Unlock()
	if fake.ParseStub != nil {
		return fake.ParseStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.parseReturns.result1, fake.parseReturns.result2
}

func (fake *ArgParser) ParseCallCount() int {
	fake.parseMutex.RLock()
	defer fake.parseMutex.RUnlock()
	return len(fake.parseArgsForCall)
}

func (fake *ArgParser) ParseArgsForCall(i int) []string {
	fake.parseMutex.RLock()
	defer fake.parseMutex.RUnlock()
	return fake.parseArgsForCall[i].arg1
}

func (fake *ArgParser) ParseReturns(result1 kiln.ApplicationConfig, result2 error) {
	fake.ParseStub = nil
	fake.parseReturns = struct {
		result1 kiln.ApplicationConfig
		result2 error
	}{result1, result2}
}

func (fake *ArgParser) ParseReturnsOnCall(i int, result1 kiln.ApplicationConfig, result2 error) {
	fake.ParseStub = nil
	if fake.parseReturnsOnCall == nil {
		fake.parseReturnsOnCall = make(map[int]struct {
			result1 kiln.ApplicationConfig
			result2 error
		})
	}
	fake.parseReturnsOnCall[i] = struct {
		result1 kiln.ApplicationConfig
		result2 error
	}{result1, result2}
}

func (fake *ArgParser) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.parseMutex.RLock()
	defer fake.parseMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ArgParser) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
